language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

os:
  - linux
  - osx
  - windows

cache: pip

before_install:
  - sudo apt-get install p7zip rar
  # NOTE: attempt to get a more updated version of file and libmagic >= 5.30
  - sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu/ bionic main restricted universe" > /etc/apt/sources.list'
  - sudo apt-get update
  - sudo apt-get install zstd
  - sudo apt-get install file libmagic1

# command to install dependencies
install:
  - pip install -q pytest-cov
  - easy_install -U -Z .

# command to run tests
script: py.test --cov=destream -v tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)
