language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

before_install:
  - sudo apt-get install p7zip rar
  - sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu/ wily main restricted" > /etc/apt/sources.list'
  - sudo apt-get update
  - sudo apt-get install file libmagic1

# command to install dependencies
install:
  - pip install -q pytest-cov
  - easy_install -U -Z .

# command to run tests
script: py.test --cov=destream -v tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)
